name: Build & Deploy CV

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Prevent hanging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Minimal LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-latex-recommended

      - name: Compile CV
        run: pdflatex -interaction=nonstopmode -halt-on-error cv.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: cv.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: cv-pdf

      - name: Deploy to Personal Site
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${{ secrets.PERSONAL_SITE_TOKEN }}@github.com/RajonDey/rd-web site
          cp cv.pdf site/public/
          cd site
          git add public/cv.pdf
          git commit -m "Update CV: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main